name: Build FreeRDP for macOS ARM64

on:
  push:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - 'CMakeLists.txt'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - 'CMakeLists.txt'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        architecture: [arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/opt/homebrew/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          brew install cmake ninja pkg-config
          brew install openssl@3 cairo json-c opus ffmpeg

      - name: Set environment variables for OpenSSL
        run: |
          echo "PKG_CONFIG_PATH=$(brew --prefix openssl@3)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Configure FreeRDP build
        run: |
          cmake -G Ninja \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=$HOME/freerdp \
            -DWITH_SAMPLE=ON \
            -DWITH_SERVER=OFF \
            -DWITH_FFMPEG=OFF \
            -DWITH_OPENH264=OFF \
            -DWITH_GSM=OFF \
            -DWITH_LAME=OFF \
            -DWITH_FAAC=OFF \
            -DWITH_OPUS=OFF \
            -DWITH_JSONC=OFF \
            -DWITH_PCSC=OFF \
            ..

      - name: Build FreeRDP
        run: |
          cmake --build . --target install

      - name: Create macOS application bundle
        run: |
          ./scripts/bundle-mac-os.sh

      - name: Upload macOS ARM64 build artifact
        uses: actions/upload-artifact@v3
        with:
          name: freerdp-arm64
          path: MacFreeRDP.app
