name: Build FreeRDP

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # 安装 Homebrew（如果尚未安装）
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          
          # 安装构建工具和依赖项
          brew install \
            ffmpeg \
            cjson \
            opus \
            cairo \
            json-c \
            libsystemd \
            pkg-config \
            cmake \
            ninja

      - name: Clone FreeRDP repository
        run: |
          git clone https://github.com/FreeRDP/FreeRDP.git
          cd FreeRDP

      - name: Create build directory
        run: |
          mkdir build
          cd build

      - name: Configure build options
        run: |
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DWITH_CAIRO=ON \
            -DWITH_FFMPEG=ON \
            -DWITH_OPUS=ON \
            -DWITH_JSONC=ON \
            -DWITH_SYSTEMD=ON \
            -G Ninja

      - name: Build and install
        run: |
          ninja
          sudo ninja install
