name: Build FreeRDP

on:
  push:
    branches:
      - '**'  # 监听所有分支的提交事件

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # 安装 Homebrew（如果尚未安装）
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # 安装构建工具和依赖项（只装 SDL2 及其 TTF）
          brew install \
            ffmpeg \
            cjson \
            opus \
            cairo \
            json-c \
            pkg-config \
            cmake \
            ninja \
            sdl2 \
            sdl2_ttf
          
      - name: Clone FreeRDP repository
        run: |
          git clone https://github.com/FreeRDP/FreeRDP.git

      - name: Create build directory
        run: |
          cd FreeRDP
          mkdir build

      - name: Configure build options
        run: |
          cd FreeRDP/build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DWITH_CAIRO=ON \
            -DWITH_FFMPEG=ON \
            -DWITH_OPUS=ON \
            -DWITH_JSONC=ON \
            -DWITH_LIBSYSTEMD=OFF \
            -DWITH_SDL2=OFF \
            -DWITH_SDL2_TTF=OFF \
            -G Ninja

      - name: Build and install
        run: |
          cd FreeRDP/build
          ninja
          sudo ninja install

