name: Build FreeRDP

on:
  push:
    branches:
      - '**'  # 监听所有分支的提交事件

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # 安装 Homebrew（如果尚未安装）
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # 安装构建工具和依赖项
          brew install \
            ffmpeg \
            cjson \
            opus \
            cairo \
            json-c \
            pkg-config \
            cmake \
            ninja \
            sdl3 \
            sdl2_ttf

      - name: Set environment variables for SDL3 and SDL2_ttf
        run: |
          echo "CMAKE_PREFIX_PATH=/opt/homebrew/opt/sdl3:/opt/homebrew/opt/sdl2_ttf:$CMAKE_PREFIX_PATH" >> $GITHUB_ENV
          echo "SDL3_DIR=/opt/homebrew/opt/sdl3/share/cmake/SDL3" >> $GITHUB_ENV
          echo "SDL2_ttf_DIR=/opt/homebrew/opt/sdl2_ttf/share/cmake/SDL2_ttf" >> $GITHUB_ENV

      - name: Clone FreeRDP repository
        run: |
          git clone https://github.com/FreeRDP/FreeRDP.git

      - name: Create build directory
        run: |
          cd FreeRDP
          mkdir build

      - name: Configure build options
        run: |
          cd FreeRDP/build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DWITH_CAIRO=ON \
            -DWITH_FFMPEG=ON \
            -DWITH_OPUS=ON \
            -DWITH_JSONC=ON \
            -DWITH_LIBSYSTEMD=OFF \
            -G Ninja

      - name: Build and install
        run: |
          cd FreeRDP/build
          ninja
          sudo ninja install
