name: Build FreeRDP

on:
  push:
    branches:
      - '**'  # 监听所有分支的提交事件

jobs:
  build:
    runs-on:  macos-13



    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # 安装 Homebrew（如果尚未安装）
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # 安装构建工具和依赖项（只装 SDL2 及其 TTF）
          brew install \
            ffmpeg \
            cjson \
            opus \
            cairo \
            json-c \
            pkg-config \
            cmake \
            ninja \
            sdl2 \
            sdl2_ttf
          
      - name: Clone FreeRDP repository
        run: |
          git clone https://github.com/FreeRDP/FreeRDP.git



      - name: Check SDL_ttf.h
        run: |
          sudo find /usr/local/ -name SDL_ttf.h


      - name: ls FreeRDP
        run: |
          ls /usr/local/Cellar/sdl2_ttf/2.24.0

      - name: ls FreeRDP
        run: |
          ls /usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2
          
      - name: Create build directory
        run: |
          cd FreeRDP
          mkdir build

      - name: Configure build options
        run: |
          cd FreeRDP/build
            cmake .. \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=/usr/local \
              -DWITH_CAIRO=ON \
              -DWITH_FFMPEG=ON \
              -DWITH_OPUS=ON \
              -DWITH_JSONC=ON \
              -DWITH_LIBSYSTEMD=OFF \
              -DWITH_SDL2=ON \
              -DWITH_SDL3=OFF \
              -DWITH_CLIENT_SDL_VERSIONED=OFF \
              -DWITH_SDL2_TTF=ON \
              -DWITH_SDL3_TTF=OFF \
              -DCMAKE_C_FLAGS="-I/usr/local/include -I/usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2 -I/System/Volumes/Data/usr/local/include -I/System/Volumes/Data/usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2" \
              -DCMAKE_CXX_FLAGS="-I/usr/local/include -I/usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2 -I/System/Volumes/Data/usr/local/include -I/System/Volumes/Data/usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2" \
              -G Ninja

      - name: Build and install
        run: |
          cd FreeRDP/build
          ninja

      - name: Copy built binary to output folder
        run: |
          ls FreeRDP/build/client/SDL/SDL2

      - name: Create archive of build directory
        run: |
          tar -czvf freerdp-build.tar.gz -C FreeRDP/build .

      - name: Upload archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: freerdp-build-artifact
          path: freerdp-build.tar.gz

        


