name: Build FreeRDP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update

      - name: Install dependencies
        run: |
          brew install cmake pkg-config cairo openssl

      - name: Configure FreeRDP with disabled Opus and FFmpeg
        run: |
          cmake -S . -B build \
            -DWITH_OPUS=OFF \
            -DWITH_FFMPEG=OFF \
            -DWITH_FAAC=OFF \
            -DWITH_FAAD2=OFF \
            -DWITH_LAME=OFF \
            -DWITH_GSM=OFF \
            -DWITH_OPENH264=OFF \
            -DWITH_JPEG=OFF \
            -DWITH_X264=OFF \
            -DWITH_OPENCL=OFF \
            -DWITH_PC=OFF \
            -DWITH_PCSC=OFF \
            -DWITH_CUPS=OFF \
            -DWITH_ALSA=OFF \
            -DWITH_PULSE=OFF \
            -DWITH_SDL=OFF \
            -DWITH_WEBVIEW_QT=OFF \
            -DWITH_WINPR_DEPRECATED=OFF

      - name: Build FreeRDP
        run: |
          cmake --build build --parallel

      - name: Install FreeRDP
        run: |
          cmake --install build
