name: Build FreeRDP

on:
  push:
    branches:
      - '**'  # 监听所有分支的提交事件

jobs:
  build:
    runs-on: macos-latest

    env:
      SDL2_TTF_INCLUDE_DIRS: /opt/homebrew/Cellar/sdl2_ttf/2.24.0/include/SDL2
      SDL2_TTF_LIBRARIES: /opt/homebrew/opt/sdl2_ttf/lib/libSDL2_ttf.dylib

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # 安装 Homebrew（如果尚未安装）
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # 安装构建工具和依赖项（只装 SDL2 及其 TTF）
          brew install \
            ffmpeg \
            cjson \
            opus \
            cairo \
            json-c \
            pkg-config \
            cmake \
            ninja \
            sdl2 \
            sdl2_ttf
          
      - name: Clone FreeRDP repository
        run: |
          git clone https://github.com/FreeRDP/FreeRDP.git


      - name: ls FreeRDP
        run: |
          ls /opt/homebrew/Cellar/sdl2_ttf/2.24.0/include/SDL2

      - name: ls FreeRDP
        run: |
          ls /opt/homebrew/opt/sdl2_ttf/lib/libSDL2_ttf.dylib
          
      - name: Create build directory
        run: |
          cd FreeRDP
          mkdir build

      - name: Configure build options
        run: |
          cd FreeRDP/build
          export CMAKE_C_FLAGS="-I/opt/homebrew/Cellar/sdl2_ttf/2.24.0/include/SDL2"
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=/usr/local \
            -DWITH_CAIRO=ON \
            -DWITH_FFMPEG=ON \
            -DWITH_OPUS=ON \
            -DWITH_JSONC=ON \
            -DWITH_LIBSYSTEMD=OFF \
            -DWITH_SDL2=OFF \
            -DWITH_SDL3=OFF \
            -DWITH_CLIENT_SDL_VERSIONED=OFF \
            -DWITH_SDL2_TTF=OFF \
            -DWITH_SDL3_TTF=OFF \
            -G Ninja

      - name: Build and install
        run: |
          cd FreeRDP/build
          export SDL2_TTF_INCLUDE_DIRS="/opt/homebrew/Cellar/sdl2_ttf/2.24.0/include/SDL2"
          export SDL2_TTF_LIBRARIES="/opt/homebrew/opt/sdl2_ttf/lib/libSDL2_ttf.dylib"
          ninja
          sudo ninja install

