name: Build FreeRDP

on:
  push:
    branches:
      - '**'  # 监听所有分支的提交事件

jobs:
  build:
    runs-on:  macos-13



    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # 安装 Homebrew（如果尚未安装）
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # 安装构建工具和依赖项（只装 SDL2 及其 TTF）
          brew install \
            ffmpeg \
            cjson \
            opus \
            cairo \
            json-c \
            pkg-config \
            cmake \
            ninja \
            sdl2 \
            sdl2_ttf
          

      - name: brew install o555
        run: |
              brew install automake


      - name: brew install openssl@3
        run: |
              git clone https://github.com/openssh/openssh-portable.git
              cd openssh-portable
              autoreconf
              ./configure --prefix=/usr/local --with-ssl-dir=$(brew --prefix openssl@3)
              make
              sudo make install


          
      - name: Clone FreeRDP repository
        run: |
          git clone https://github.com/FreeRDP/FreeRDP.git
      - name: Check SDL_ttf.h
        run: |
          sudo find /usr/local/ -name SDL_ttf.h
      - name: ls FreeRDP
        run: |
          ls /usr/local/Cellar/sdl2_ttf/2.24.0
      - name: ls FreeRDP
        run: |
          ls /usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2
          
      - name: Create build directory
        run: |
          cd FreeRDP
          mkdir build

      - name: Configure build options
        run: |
          cd FreeRDP/build
          cmake .. \
               -DCMAKE_BUILD_TYPE=Release \
               -DCMAKE_INSTALL_PREFIX=${PWD}/bundle \
               -DWITH_CAIRO=ON \
               -DWITH_FFMPEG=ON \
               -DWITH_OPUS=ON \
               -DWITH_JSONC=ON \
               -DWITH_LIBSYSTEMD=OFF \
               -DWITH_SDL2=OFF \
               -DWITH_SDL3=ON \
               -DWITH_CLIENT_SDL_VERSIONED=OFF \
               -DWITH_SDL2_TTF=OFF \
               -DWITH_SDL3_TTF=ON \
               -DWITH_OPENSSL=ON \
               -DOPENSSL_ROOT_DIR=$(brew --prefix openssl@3) \
               -DBUILD_SHARED_LIBS=OFF \
               -DWITH_STATIC_CHANNELS=ON \
               -DWITH_STATIC_PLUGINS=ON \
               -DCMAKE_EXE_LINKER_FLAGS="" \
               -DCMAKE_C_FLAGS="-I/usr/local/include \
                                -I/usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2 \
                                -I/System/Volumes/Data/usr/local/include \
                                -I/System/Volumes/Data/usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2" \
               -DCMAKE_CXX_FLAGS="-I/usr/local/include \
                                  -I/usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2 \
                                  -I/System/Volumes/Data/usr/local/include \
                                  -I/System/Volumes/Data/usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2" \
               -G Ninja

      - name: Build and install
        run: |
          cd FreeRDP/build
          ninja
          ninja install

      - name: Create .app bundle directory
        run: |
          mkdir -p MyFreeRDP.app/Contents/MacOS
          mkdir -p MyFreeRDP.app/Contents/Frameworks
          mkdir -p MyFreeRDP.app/Contents/Resources
          # 复制 SDL3 客户端二进制并重命名为可执行文件
          cp FreeRDP/build/bundle/bin/sdl3-freerdp MyFreeRDP.app/Contents/MacOS/sdl3-freerdp

      - name: Create Info.plist
        run: |
          cat <<EOF > MyFreeRDP.app/Contents/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
             "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>CFBundleExecutable</key>
              <string>sdl3-freerdp</string>
              <key>CFBundleIdentifier</key>
              <string>org.freerdp.sdl3</string>
              <key>CFBundleName</key>
              <string>FreeRDP SDL3</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
          </dict>
          </plist>
          EOF

      - name: Install dylibbundler
        run: |
          brew install dylibbundler

      - name: Bundle dylibs with dylibbundler
        run: |
          dylibbundler -od -b \
            -x MyFreeRDP.app/Contents/MacOS/sdl3-freerdp \
            -d MyFreeRDP.app/Contents/Frameworks \
            -p @executable_path/../Frameworks

      - name: Zip MyFreeRDP.app
        run: |
          ditto -c -k --sequesterRsrc --keepParent MyFreeRDP.app MyFreeRDP.zip

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: freerdp-zip
          path: MyFreeRDP.zip
