name: Build FreeRDP

on:
  push:
    branches:
      - '**'  # 监听所有分支的提交事件

jobs:
  build:
    runs-on:  macos-13



    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          # 安装 Homebrew（如果尚未安装）
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          # 安装构建工具和依赖项（只装 SDL2 及其 TTF）
          brew install \
            ffmpeg \
            cjson \
            opus \
            cairo \
            json-c \
            pkg-config \
            cmake \
            ninja \
            sdl2 \
            sdl2_ttf
          
      - name: brew install o555
        run: |
              brew install automake
      - name: brew install openssl@3
        run: |
              git clone https://github.com/openssh/openssh-portable.git
              cd openssh-portable
              autoreconf
              ./configure --prefix=/usr/local --with-ssl-dir=$(brew --prefix openssl@3)
              make
              sudo make install
          
      - name: Clone FreeRDP repository
        run: |
          git clone https://github.com/FreeRDP/FreeRDP.git
      - name: Check SDL_ttf.h
        run: |
          sudo find /usr/local/ -name SDL_ttf.h
      - name: ls FreeRDP
        run: |
          ls /usr/local/Cellar/sdl2_ttf/2.24.0
      - name: ls FreeRDP
        run: |
          ls /usr/local/Cellar/sdl2_ttf/2.24.0/include/SDL2
          
      - name: Create build directory
        run: |
          cd FreeRDP
          mkdir build
      - name: Configure build options
        run: |
          cd FreeRDP/build
           cmake .. \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=${PWD}/bundle \
                -DWITH_CAIRO=ON \
                -DWITH_FFMPEG=ON \
                -DWITH_OPUS=ON \
                -DWITH_JSONC=ON \
                -DWITH_LIBSYSTEMD=OFF \
                -DWITH_SDL2=ON \
                -DWITH_SDL3=OFF \
                -DWITH_CLIENT_SDL_VERSIONED=OFF \
                -DWITH_SDL2_TTF=ON \
                -DWITH_SDL3_TTF=OFF \
                -DWITH_OPENSSL=ON \
                -DOPENSSL_ROOT_DIR=$(brew --prefix openssl@3) \
                -DBUILD_SHARED_LIBS=OFF \
                -DWITH_STATIC_CHANNELS=ON \
                -DWITH_STATIC_PLUGINS=ON \
                -DCMAKE_EXE_LINKER_FLAGS="" \
                -G Ninja


      - name: Download & mount SDL2.dmg
        run: |
          curl -L -o SDL2-2.0.22.dmg https://github.com/libsdl-org/SDL/releases/download/release-2.0.22/SDL2-2.0.22.dmg
          hdiutil attach SDL2-2.0.22.dmg -nobrowse -quiet
          mkdir -p SDL2-macos
          cp -R /Volumes/SDL2/SDL2.framework SDL2-macos/
          hdiutil detach /Volumes/SDL2 -quiet

      - name: Download & mount SDL2_ttf.dmg
        run: |
          curl -L -o SDL2_ttf-2.0.18.dmg https://github.com/libsdl-org/SDL_ttf/releases/download/release-2.0.18/SDL2_ttf-2.0.18.dmg
          hdiutil attach SDL2_ttf-2.0.18.dmg -nobrowse -quiet
          mkdir -p SDL2_ttf-macos
          cp -R /Volumes/SDL2_ttf/SDL2_ttf.framework SDL2_ttf-macos/
          hdiutil detach /Volumes/SDL2_ttf -quiet

      - name: Create .app bundle structure
        run: |
          ls FreeRDP/build/bundle/bin

      - name: Create .app bundle structure
        run: |
          mkdir -p MyFreeRDP.app/Contents/{MacOS,Frameworks,Resources}
          cp FreeRDP/build/bundle/bin/sdl-freerdp MyFreeRDP.app/Contents/MacOS/
          cp -R SDL2-macos/SDL2.framework MyFreeRDP.app/Contents/Frameworks/
          cp -R SDL2_ttf-macos/SDL2_ttf.framework MyFreeRDP.app/Contents/Frameworks/


      - name: Fix rpath on sdl-freerdp
        run: |
          install_name_tool \
            -add_rpath @executable_path/../Frameworks \
            MyFreeRDP.app/Contents/MacOS/sdl-freerdp

      - name: Bundle remaining dylibs
        run: |
          dylibbundler \
            -od -b \
            -x MyFreeRDP.app/Contents/MacOS/sdl-freerdp \
            -d MyFreeRDP.app/Contents/Frameworks \
            -p @executable_path/../Frameworks


      - name: Create Info.plist
        run: |
          cat <<EOF > MyFreeRDP.app/Contents/Info.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
            "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>CFBundleExecutable</key>
              <string>sdl-freerdp</string>
              <key>CFBundleIdentifier</key>
              <string>org.freerdp.sdl</string>
              <key>CFBundleName</key>
              <string>FreeRDP SDL</string>
              <key>CFBundleVersion</key>
              <string>1.0</string>
            </dict>
          </plist>
          EOF

      - name: Zip MyFreeRDP.app
        run: |
          ditto -c -k --sequesterRsrc --keepParent \
            MyFreeRDP.app MyFreeRDP.zip

      - name: Upload ZIP
        uses: actions/upload-artifact@v4
        with:
          name: freerdp-zip
          path: MyFreeRDP.zip
